services:
  postgres:
    image: ${POSTGRES_IMAGE:-postgis/postgis:13-3.2}
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
      - postgres:/var/lib/postgresql/data

  redis:
    image: ${REDIS_IMAGE:-redis:7-alpine}
    volumes:
      - redis:/data

  usershub:
    image: ${USERSHUB_IMAGE:-ghcr.io/pnx-si/usershub:latest}
    build: ./UsersHub/
    depends_on:
      - postgres
    volumes:
      - ./config/usershub/:/dist/config/
    user: ${UID:-1000}:${GID:-1000}
    environment:
      - USERSHUB_URL_APPLICATION="${BASE_URL}${USERSHUB_PREFIX}"
      - USERSHUB_SQLALCHEMY_DATABASE_URI=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - USERSHUB_SETTINGS=${USERSHUB_SETTINGS:-config.py}
      - PYTHONPATH=/dist/config
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.usershub.rule=Host(`${HOST}`) && PathPrefix(`${USERSHUB_PREFIX}`)"
      - "traefik.http.routers.usershub.entrypoints=web"

  taxhub:
    image: ${TAXHUB_IMAGE:-ghcr.io/pnx-si/taxhub:latest}
    build: ./TaxHub/
    depends_on:
      - postgres
    volumes:
      - ./config/taxhub/:/dist/config/
    user: ${UID:-1000}:${GID:-1000}
    environment:
      - TAXHUB_APPLICATION_ROOT="${TAXHUB_PREFIX}"
      - TAXHUB_SQLALCHEMY_DATABASE_URI=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - TAXHUB_SETTINGS=${TAXHUB_SETTINGS:-config.py}
      - PYTHONPATH=/dist/config
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.taxhub.rule=Host(`${HOST}`) && PathPrefix(`${TAXHUB_PREFIX}`)"
      - "traefik.http.routers.taxhub.entrypoints=web"

  geonature-backend:
    image: ${GEONATURE_BACKEND_IMAGE:-ghcr.io/pnx-si/geonature-backend:latest}
    build:
      context: ./GeoNature/
      dockerfile: ./backend/Dockerfile
      target: prod-full
    depends_on:
      - postgres
      - redis
    volumes:
      - ./config/geonature/:/dist/config/
    user: ${UID:-1000}:${GID:-1000}
    environment:
      - GEONATURE_SQLALCHEMY_DATABASE_URI=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - GEONATURE_SECRET_KEY="8a7d773f1153193a388511de4cfe2535"
      - GEONATURE_URL_APPLICATION="${BASE_URL}${GEONATURE_PREFIX}"
      - GEONATURE_API_ENDPOINT="${BASE_URL}${GEONATURE_API_PREFIX}"
      - GEONATURE_API_TAXHUB="${BASE_URL}${TAXHUB_API_PREFIX}"
    #  - GEONATURE_CONFIG_FILE=${GEONATURE_CONFIG_FILE:-/dist/config/geonature_config.toml}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.geonature-api.rule=Host(`${HOST}`) && PathPrefix(`${GEONATURE_API_PREFIX}`)"
      - "traefik.http.routers.geonature-api.entrypoints=web"

  geonature-frontend:
    image: ${GEONATURE_FRONTEND_IMAGE:-ghcr.io/pnx-si/geonature-frontend:latest}
    build:
      context: ./GeoNature/
      dockerfile: ./frontend/Dockerfile
      target: prod-full
    environment:
      - NGINX_LOCATION=${GEONATURE_PREFIX}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.geonature.rule=Host(`${HOST}`) && PathPrefix(`${GEONATURE_PREFIX}`)"
      - "traefik.http.routers.geonature.entrypoints=web"

  traefik:
    image: traefik:2.9
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
    volumes:
      #- ./config/traefik/:/etc/traefik/
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - ${HTTP_PORT:-80}:80
      - ${HTTPS_PORT:-443}:443

volumes:
  postgres:
  redis:
